#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HANDSHAKE_PORT 8492
#define BUF_SIZE 500
#define PROTOCOL_LEN 100
#define RESERVED_LEN 100
#define IP_LEN 20
#define LISTENING_PORT 4732
#define MAX_PEER_NUM 20
#define MAX_FILE_NUM 100
#define ALIVE_POLLING_TIME 60
#define ALIVE_TIMEOUT 600
#define FILE_NAME_MAX_LEN 127
#define INTERVAL 3
#define PIECE_LENGTH 500
#define MD5_LEN 32
#define MAX_MONITOR_DIR 100

// added by gjj
#define P2P_LISTENING_PORT 3100
#define P2P_DOWNLOAD_PORT 4100
#define P2P_DOWNLOAD_PORT_MAX 5100
#define PIECE_SIZE 1024 // as 1 kB
#define OPEN_FILE_TIMEOUT 5
#define WAIT_PEER_INTERVAL 1
#define WAIT_PIECE_INTERVAL 10
#define WAIT_THREAD_INTERVAL 1
#define WAIT_NET_UP_INTERVAL 5
#define MAX_THREAD_NUM 99

#endif
