#ifndef DARTSYNCCONFIG
#define DARTSYNCCONFIG

#define P2P_LISTENING_PORT 3100
#define P2P_DOWNLOAD_PORT 4100
#define P2P_DOWNLOAD_PORT_MAX 5100
#define PIECE_SIZE 10240 // as 10 byte
#define OPEN_FILE_TIMEOUT 5
#define WAIT_PEER_INTERVAL 1
#define WAIT_PIECE_INTERVAL 10
#define WAIT_THREAD_INTERVAL 1
#define WAIT_NET_UP_INTERVAL 5
#define MAX_THREAD_NUM 99
#define FILE_NAME_LEN 1024
#define IP_LEN 16  // length of IP

#endif